server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    #yml文件配置路由
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供服务的路由地址 集群版 CLOUD-PAYMENT-SERVICE是在服务注册发现中心的名称
                                          #也是服务端的名称 8001 8002 spring application name
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
            #- After=2023-04-08T10:59:34.102+08:00[Asia/Shanghai]
            #- Before=2023-04-08T10:59:34.102+08:00[Asia/Shanghai]
            #- Between=2023-04-08T10:59:34.102+08:00[Asia/Shanghai] ,  2023-04-08T10:59:34.102+08:00[Asia/Shanghai]
                #            curl http://localhost:9527/payment/lb --cookie "username=zzyy"
            #- Cookie=username,zzyy   #Cookie=cookieName,正则表达式
              # 请求头要有X-Request-Id属性并且值为整数的正则表达式 curl http://localhost:9527/payment/lb --cookie "username=zzyy" -H "X-Request-Id:11"
            #- Header=X-Request-Id, \d+
            #- Host=**.atguigu.com  # curl http://localhost:9527/payment/lb -H "Host:afae.atguigu.com"

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka